M48
; DRILL file {KiCad (6.0.4-0)} date 
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-16T18:03:32-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.400
%
G90
G05
T1
X107.0Y-75.137
X107.0Y-77.887
X107.0Y-114.495
X107.0Y-117.245
T2
X202.0Y-96.186
X208.0Y-96.186
T3
X145.815Y-82.475
X145.815Y-90.275
T0
M30
